name: sub-domain

services:
  sub-domain-demystifydigital-app:
    container_name: sub-domain-demystifydigital-app
    build:
      context: .
      dockerfile: ./dockerfiles/8.1
    privileged: true
    env_file: env/all.env
    environment:
      - DEBUG=1
      - PHP_MEMORY_LIMIT=6144M
    ports:
      - 3000:80
    volumes:
      - ./src:/var/www/html

  sub-domain-demystifydigital-db:
    container_name: sub-domain-demystifydigital-db
    image: mariadb:10.6
    command: --max_allowed_packet=64M --optimizer_use_condition_selectivity=1 --optimizer_switch="rowid_filter=off" --skip-ssl
    env_file: env/db.env
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  sub-domain-demystifydigital-redis:
    container_name: sub-domain-demystifydigital-redis
    image: redis:7.4.1
    env_file: env/redis.env

  sub-domain-demystifydigital-opensearch:
    container_name: sub-domain-demystifydigital-opensearch
    image: opensearchproject/opensearch:2.12.0
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "max_map_count=262144"

  sub-domain-demystifydigital-rabbitmq:
    container_name: sub-domain-demystifydigital-rabbitmq
    image: rabbitmq:4
    volumes:
      - ./.docker/rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env
